/* =========================================================================
   THE PARKER LEARNING HUB — shared app logic
   Do not edit this file to update weekly content — edit content.js instead.
   ========================================================================= */

/* ---------------- Icon system (hand-drawn inline SVG, no external files) ---------------- */
const ICONS = {
  home:        '<path d="M3 11l9-8 9 8"/><path d="M5 10v10h14V10"/><path d="M9 20v-6h6v6"/>',
  clipboard:   '<rect x="6" y="4" width="12" height="17" rx="2"/><rect x="9" y="2" width="6" height="4" rx="1"/><line x1="9" y1="10" x2="15" y2="10"/><line x1="9" y1="14" x2="15" y2="14"/><line x1="9" y1="18" x2="13" y2="18"/>',
  heart:       '<path d="M12 21S4.5 16.2 2.6 11.6C1.2 8.2 3 5 6.2 5c1.9 0 3.3 1 4.1 2.3C11.1 6 12.5 5 14.4 5 17.6 5 19.4 8.2 18 11.6 16.1 16.2 12 21 12 21z"/>',
  megaphone:   '<path d="M3 10v4l4 1 9 4V5l-9 4-4 1z"/><path d="M17 9a4 4 0 010 6"/>',
  book:        '<path d="M3 5c3-1.5 6-1.5 9 0v14c-3-1.5-6-1.5-9 0V5z"/><path d="M21 5c-3-1.5-6-1.5-9 0v14c3-1.5 6-1.5 9 0V5z"/>',
  pencil:      '<path d="M4 20l1-4L16 5l3 3L8 19l-4 1z"/><line x1="14" y1="7" x2="17" y2="10"/>',
  chat:        '<path d="M4 5h16v11H8l-4 4V5z"/>',
  monitor:     '<rect x="3" y="4" width="18" height="12" rx="2"/><line x1="8" y1="20" x2="16" y2="20"/><line x1="12" y1="16" x2="12" y2="20"/>',
  users:       '<circle cx="9" cy="8" r="3"/><path d="M3 20c0-3.3 2.7-6 6-6s6 2.7 6 6"/><circle cx="17" cy="9" r="2.4"/><path d="M15.2 20c0-2.2 1-4 2.8-5"/>',
  target:      '<circle cx="12" cy="12" r="8"/><circle cx="12" cy="12" r="4.5"/><circle cx="12" cy="12" r="1"/>',
  'check-circle':'<circle cx="12" cy="12" r="9"/><path d="M8 12.5l2.7 2.7L16.5 9"/>',
  calendar:    '<rect x="3" y="5" width="18" height="16" rx="2"/><line x1="3" y1="10" x2="21" y2="10"/><line x1="8" y1="3" x2="8" y2="7"/><line x1="16" y1="3" x2="16" y2="7"/>',
  mail:        '<rect x="3" y="5" width="18" height="14" rx="2"/><path d="M3 6l9 7 9-7"/>',
  globe:       '<circle cx="12" cy="12" r="9"/><line x1="3" y1="12" x2="21" y2="12"/><path d="M12 3c3 3.5 3 14.5 0 18M12 3c-3 3.5-3 14.5 0 18"/>',
  camera:      '<rect x="3" y="7" width="18" height="13" rx="2"/><path d="M8 7l1.4-3h5.2L16 7"/><circle cx="12" cy="13.5" r="3.4"/>',
  star:        '<path d="M12 2.5l3 6.4 6.8.9-5 4.9 1.2 6.8L12 18l-6 3.5 1.2-6.8-5-4.9 6.8-.9z"/>',
  'trending-up':'<path d="M3 17l6-6 4 4 8-8"/><path d="M15 6h6v6"/>',
  menu:        '<line x1="4" y1="7" x2="20" y2="7"/><line x1="4" y1="12" x2="20" y2="12"/><line x1="4" y1="17" x2="20" y2="17"/>',
  close:       '<line x1="6" y1="6" x2="18" y2="18"/><line x1="18" y1="6" x2="6" y2="18"/>',
  mappin:      '<path d="M12 21s7-7.8 7-12.4A7 7 0 105 8.6C5 13.2 12 21 12 21z"/><circle cx="12" cy="8.6" r="2.3"/>',
  award:       '<circle cx="12" cy="8" r="5"/><path d="M8.3 12.7L6.6 21l5.4-3.2L17.4 21l-1.7-8.3"/>'
};
function icon(name, size){
  size = size || 20;
  const body = ICONS[name] || ICONS.star;
  return '<svg class="icon" width="'+size+'" height="'+size+'" viewBox="0 0 24 24" fill="none" ' +
         'stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">'+body+'</svg>';
}
function iconize(root){
  (root||document).querySelectorAll('[data-icon]').forEach(function(el){
    const size = el.getAttribute('data-icon-size') || 20;
    el.innerHTML = icon(el.getAttribute('data-icon'), size);
  });
}

/* ---------------- Nav + footer (shared across all pages) ---------------- */
const NAV_ITEMS = [
  { page: 'brief',  href: 'index.html',  label: 'Instructional Brief', icon: 'clipboard' },
  { page: 'family', href: 'family.html', label: 'Family Connection',   icon: 'heart' },
  { page: 'news',   href: 'news.html',   label: 'Classroom News',      icon: 'megaphone' }
];

function renderChrome(){
  const current = document.body.getAttribute('data-page');

  const navHtml = NAV_ITEMS.map(function(item){
    const cls = item.page === current ? 'active' : '';
    return '<a href="'+item.href+'" class="'+cls+'"><span data-icon="'+item.icon+'" data-icon-size="16"></span>'+item.label+'</a>';
  }).join('');

  document.querySelectorAll('[data-slot="nav"]').forEach(function(el){
    el.innerHTML =
      '<div class="nav-inner">' +
        '<div class="brand"><div class="mark">P</div>' +
          '<div class="txt"><div class="name">The Parker Learning Hub</div>' +
          '<div class="sub">'+CONTENT.meta.school+'</div></div></div>' +
        '<nav class="links" id="navLinks">'+navHtml+'</nav>' +
        '<button class="nav-toggle" id="navToggle" aria-label="Open menu"><span data-icon="menu" data-icon-size="24"></span></button>' +
      '</div>';
  });

  document.querySelectorAll('[data-slot="footer"]').forEach(function(el){
    el.innerHTML =
      '<div class="container">' +
        '<div class="vision-title">'+CONTENT.meta.teacherName+'\u2019s Classroom Vision</div>' +
        '<p>Every lesson is intentionally designed to build strong readers, critical thinkers, confident writers, ' +
        'and collaborative learners. Through rigorous instruction, meaningful discussion, and evidence-based thinking, ' +
        'students develop the knowledge and skills necessary for success in school and beyond.</p>' +
        '<div class="foot-links">' + NAV_ITEMS.map(function(i){ return '<a href="'+i.href+'">'+i.label+'</a>'; }).join('') +
        '<a href="mailto:'+ (CONTENT.family && CONTENT.family.resources && CONTENT.family.resources[0] ? CONTENT.family.resources[0].href.replace('mailto:','') : 'parker@example.edu') +'">Email '+CONTENT.meta.teacherName+'</a></div>' +
        '<div class="foot-bottom">'+CONTENT.meta.school+' \u00B7 '+CONTENT.meta.gradeSubject+'</div>' +
      '</div>';
  });

  iconize(document);

  const toggle = document.getElementById('navToggle');
  const links = document.getElementById('navLinks');
  if(toggle && links){
    toggle.addEventListener('click', function(){
      links.classList.toggle('open');
      toggle.innerHTML = icon(links.classList.contains('open') ? 'close' : 'menu', 24);
    });
  }
}

function heroArtSVG(){
  // Abstract, non-photographic illustration — deliberately not a depiction of real students.
  return '<svg viewBox="0 0 200 200" fill="none">' +
    '<circle cx="100" cy="100" r="92" fill="rgba(201,151,31,0.14)"/>' +
    '<circle cx="100" cy="100" r="66" fill="rgba(255,255,255,0.06)"/>' +
    '<path d="M55 120c8-30 20-46 45-46s37 16 45 46" stroke="#C9971F" stroke-width="4" stroke-linecap="round" fill="none"/>' +
    '<rect x="70" y="118" width="60" height="10" rx="5" fill="#C9971F"/>' +
    '<rect x="80" y="132" width="40" height="7" rx="3.5" fill="rgba(255,255,255,0.55)"/>' +
    '<circle cx="70" cy="76" r="9" fill="#0E8A93"/>' +
    '<circle cx="130" cy="76" r="9" fill="#2F8F5B"/>' +
    '<circle cx="100" cy="60" r="9" fill="#fff"/>' +
    '</svg>';
}

function renderHero(pageEyebrow){
  const slot = document.querySelector('[data-slot="hero"]');
  if(!slot) return;
  slot.innerHTML =
    '<div class="container hero-inner">' +
      '<div class="hero-text reveal">' +
        '<p class="eyebrow">'+pageEyebrow+'</p>' +
        '<h1>The Parker Learning Hub</h1>' +
        '<p class="school">'+CONTENT.meta.school+'</p>' +
        '<p class="grade">'+CONTENT.meta.gradeSubject+'</p>' +
        '<p class="tagline">\u201C'+CONTENT.meta.tagline+'\u201D</p>' +
        '<div class="week-chip"><span data-icon="calendar" data-icon-size="15"></span>Week of '+CONTENT.meta.weekOf+'</div>' +
      '</div>' +
      '<div class="hero-art reveal">'+heroArtSVG()+'</div>' +
    '</div>';
  iconize(slot);
}

/* ---------------- helpers ---------------- */
function listHTML(items){ return items.map(function(t){ return '<li>'+t+'</li>'; }).join(''); }
function checkListHTML(items){
  const tick = '<svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="currentColor" ' +
               'stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round"><path d="M5 13l4 4 10-10"/></svg>';
  return '<ul class="check-list">' + items.map(function(t){
    return '<li><span class="tick">'+tick+'</span><span>'+t+'</span></li>';
  }).join('') + '</ul>';
}
function plainListHTML(items){ return '<ul class="plain-list">' + listHTML(items) + '</ul>'; }

/* ============================= PAGE: BRIEF ============================= */
function renderBrief(){
  renderHero('For Principals \u00B7 Instructional Coaches \u00B7 District Leaders');
  const b = CONTENT.brief;

  document.querySelector('[data-slot="curriculum-overview"]').innerHTML =
    '<h3>'+b.moduleTitle+'</h3>' +
    '<p class="section-sub" style="margin-bottom:14px;"><strong>Essential Question:</strong> '+b.essentialQuestion+'</p>' +
    '<div class="grid grid-2">' +
      '<div><h4 style="font-size:12.5px;text-transform:uppercase;letter-spacing:.05em;color:var(--teal-deep);margin:0 0 8px;">Lessons this week</h4>'+plainListHTML(b.lessonsThisWeek)+'</div>' +
      '<div><h4 style="font-size:12.5px;text-transform:uppercase;letter-spacing:.05em;color:var(--teal-deep);margin:0 0 8px;">Texts students will read</h4>'+plainListHTML(b.textsThisWeek)+'</div>' +
    '</div>';

  document.querySelector('[data-slot="today-instruction"]').innerHTML =
    '<div class="grid grid-2" style="margin-bottom:16px;">' +
      '<div><div class="htag">Today\u2019s lesson</div><div style="font-weight:700;font-size:14.5px;">'+b.today.lesson+'</div></div>' +
      '<div><div class="htag">Learning target</div><div style="font-weight:700;font-size:14.5px;">'+b.today.learningTarget+'</div></div>' +
      '<div><div class="htag">MSDE standards</div><div style="font-weight:700;font-size:14.5px;">'+b.today.standards+'</div></div>' +
    '</div>' +
    '<div class="htag" style="margin-bottom:8px;">Success criteria — students will:</div>' +
    checkListHTML(b.today.successCriteria);

  document.querySelector('[data-slot="exit-ticket"]').innerHTML = plainListHTML(b.exitTicket);
  document.querySelector('[data-slot="visitors-see"]').innerHTML = checkListHTML(b.visitorsShouldSee);

  document.querySelector('[data-slot="stations"]').innerHTML = b.stations.map(function(s){
    return '<div class="card station reveal">' +
      '<div class="chip teal" style="width:34px;height:34px;"><span data-icon="'+s.icon+'" data-icon-size="17"></span></div>' +
      '<h4>'+s.name+'</h4><ul>'+s.tasks.map(function(t){return '<li>'+t+'</li>';}).join('')+'</ul>' +
    '</div>';
  }).join('');

  const a = b.attendance;
  document.querySelector('[data-slot="attendance"]').innerHTML =
    '<div class="goal-ring-wrap">' +
      '<div class="goal-ring" style="--pct:'+a.today+'"><div class="val"><b>'+a.today+'%</b><span>Today</span></div></div>' +
      '<div class="goal-stats">' +
        '<div class="g"><b>'+a.goal+'%</b><span>Daily goal</span></div>' +
        '<div class="g"><b>'+a.weeklyAverage+'%</b><span>Weekly average</span></div>' +
      '</div>' +
    '</div>';

  iconize(document);
}

/* ============================= PAGE: FAMILY ============================= */
function renderFamily(){
  renderHero('For Parents \u00B7 Caregivers \u00B7 Families');
  const f = CONTENT.family;

  document.querySelector('[data-slot="message"]').innerHTML =
    '<p style="margin:0 0 6px;font-size:14.5px;">'+f.message+'</p>' +
    '<div class="signature">\u2014 '+CONTENT.meta.teacherName+'</div>';

  const w = f.thisWeek;
  document.querySelector('[data-slot="this-week"]').innerHTML =
    '<div class="grid grid-2">' +
      '<div><div class="htag">Current module</div><div style="font-weight:700;">'+w.module+'</div></div>' +
      '<div><div class="htag">Current lesson</div><div style="font-weight:700;">'+w.lesson+'</div></div>' +
      '<div><div class="htag">Essential question</div><div style="font-weight:700;">'+w.essentialQuestion+'</div></div>' +
      '<div><div class="htag">Learning target</div><div style="font-weight:700;">'+w.learningTarget+'</div></div>' +
    '</div>';

  document.querySelector('[data-slot="conversation-starters"]').innerHTML = plainListHTML(f.conversationStarters);

  document.querySelector('[data-slot="vocab"]').innerHTML =
    '<table class="vocab"><thead><tr><th>Word</th><th>Meaning</th></tr></thead><tbody>' +
    f.vocabulary.map(function(v){ return '<tr><td class="word">'+v.word+'</td><td>'+v.meaning+'</td></tr>'; }).join('') +
    '</tbody></table>';

  document.querySelector('[data-slot="reading-home"]').innerHTML =
    '<p style="margin:0 0 10px;font-size:14px;">Students should read for at least <strong>'+f.readingAtHome.minutes+' minutes</strong> every evening.</p>' +
    '<div class="htag" style="margin-bottom:6px;">Families can ask:</div>' + plainListHTML(f.readingAtHome.questions);

  const im = f.important;
  function col(title, items){ return '<div class="dates-col"><h4>'+title+'</h4>'+plainListHTML(items.length?items:['Nothing scheduled'])+'</div>'; }
  document.querySelector('[data-slot="important-dates"]').innerHTML =
    '<div class="dates-grid">' +
      col('Homework', im.homework) + col('Projects', im.projects) +
      col('Assessments', im.assessments) + col('Field trips', im.fieldTrips) +
      col('School events', im.events) + col('Spirit days', im.spiritDays) +
      col('Reminders', im.reminders) +
    '</div>';

  document.querySelector('[data-slot="celebrations"]').innerHTML =
    '<div class="badge-row">' + f.celebrations.map(function(c){
      return '<div class="badge"><span data-icon="'+c.icon+'" data-icon-size="16"></span>'+c.text+'</div>';
    }).join('') + '</div>';

  document.querySelector('[data-slot="resources"]').innerHTML =
    '<div class="resource-grid">' + f.resources.map(function(r){
      return '<a class="resource-btn" href="'+r.href+'"><div class="chip teal"><span data-icon="'+r.icon+'" data-icon-size="15"></span></div>'+r.label+'</a>';
    }).join('') + '</div>';

  iconize(document);
}

/* ============================= PAGE: NEWS ============================= */
function photoSlotEmpty(label){
  return '<div class="photo-slot"><span data-icon="camera" data-icon-size="22"></span>'+label+' coming soon</div>';
}
function photoGrid(list, label){
  const cells = list.length ? list.map(function(src){ return '<div class="photo-slot"><img src="'+src+'" alt="'+label+'"></div>'; })
                            : [photoSlotEmpty(label), photoSlotEmpty(label), photoSlotEmpty(label)];
  return '<div class="photo-grid">'+cells.join('')+'</div>';
}

function renderNews(){
  renderHero('Classroom News \u00B7 Photos \u00B7 Updates');
  const n = CONTENT.news;

  document.querySelector('[data-slot="newsletter"]').innerHTML =
    '<div class="feed-meta">Weekly Newsletter</div><h3 style="margin:0 0 8px;">'+n.newsletter.title+'</h3>' +
    '<p style="margin:0;font-size:14px;">'+n.newsletter.body+'</p>';

  document.querySelector('[data-slot="events"]').innerHTML = n.events.map(function(e){
    return '<div class="event-row"><div class="event-date">'+e.date+'</div><div><h4>'+e.title+'</h4><p>'+e.detail+'</p></div></div>';
  }).join('');

  document.querySelector('[data-slot="announcements"]').innerHTML = plainListHTML(n.announcements);

  document.querySelector('[data-slot="photos-anchor"]').innerHTML = photoGrid(n.photos.anchorCharts, 'Anchor chart photo');
  document.querySelector('[data-slot="photos-work"]').innerHTML = photoGrid(n.photos.studentWork, 'Student work (names removed)');
  document.querySelector('[data-slot="photos-stations"]').innerHTML = photoGrid(n.photos.stations, 'Learning station photo');

  document.querySelector('[data-slot="field-trip"]').innerHTML =
    '<h3 style="margin:0 0 6px;">'+n.fieldTrip.title+'</h3>' +
    '<div class="htag" style="margin-bottom:8px;">'+n.fieldTrip.date+'</div>' +
    '<p style="margin:0;font-size:14px;">'+n.fieldTrip.detail+'</p>';

  const rc = n.readingChallenge;
  const pct = Math.min(100, Math.round((rc.booksReadSoFar / rc.goalBooks) * 100));
  document.querySelector('[data-slot="reading-challenge"]').innerHTML =
    '<div style="display:flex;justify-content:space-between;font-size:13px;font-weight:700;margin-bottom:8px;">' +
      '<span>'+rc.booksReadSoFar+' of '+rc.goalBooks+' books</span><span>'+pct+'%</span></div>' +
    '<div class="progress-bar"><div style="width:'+pct+'%"></div></div>' +
    '<p style="margin:12px 0 0;font-size:13px;color:var(--muted);">'+rc.note+'</p>';

  iconize(document);
}

/* ---------------- boot ---------------- */
document.addEventListener('DOMContentLoaded', function(){
  renderChrome();
  const page = document.body.getAttribute('data-page');
  if(page === 'brief') renderBrief();
  if(page === 'family') renderFamily();
  if(page === 'news') renderNews();
});
